{% set name = "pypinfo" %}
{% set version = "23.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pypinfo-{{ version }}.tar.gz
  sha256: 01448119be02a363d50664fc45e44cf279627ee27092baea9a466d41eaf71653

build:
  entry_points:
    - pypinfo = pypinfo.cli:pypinfo
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - binary
    - click
    - google-cloud-bigquery-core >=2.11.0
    - packaging >=16.2
    - platformdirs
    - tinydb >=4
    - tinyrecord >=0.2.0

test:
  imports:
    - pypinfo
  commands:
    - pip check
    - pypinfo --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: View PyPI download statistics with ease.
  home: https://github.com/ofek/pypinfo
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
